// import { Providers } from '@/components/providers'
import { authOptions } from '@/libs/next-auth'
import type { Metadata } from 'next'
// import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Providers session={session}> */}
          {children}
        {/* </Providers> */}
      </body>
    </html>
  )
}
